#!/bin/sh

message=${1?Error: no message given}
currentBranch=$(git symbolic-ref --short -q HEAD)

if [ ! -z "$1" ];
then
  git add .
  git commit -m "$message"
  git push origin $currentBranch
else
  echo "Commit message is not provided"
fi